export const queryKeys = {
  profile: ['profile'] as const,
  dashboard: ['dashboard'] as const,
  goals: ['goals'] as const,
  goal: (id: string) => ['goals', id] as const,
  transactions: ['transactions'] as const,
  goalTransactions: (goalId: string) => ['transactions', 'goal', goalId] as const,
  withdrawals: ['withdrawals'] as const,
  notifications: ['notifications'] as const,
  unreadCount: ['notifications', 'unread'] as const,
  depositRequests: ['deposit-requests'] as const,
  myDepositRequests: ['my-deposit-requests'] as const,
  adminWithdrawals: ['admin', 'withdrawals'] as const,
  adminMetrics: ['admin', 'metrics'] as const,
  adminUsers: ['admin', 'users'] as const,
  penaltySettings: ['penalty-settings'] as const,
  platformSettings: ['platform-settings'] as const,
  financePosts: (savedOnly?: boolean) => ['finance-posts', { savedOnly: !!savedOnly }] as const,
  financeComments: (postId: string) => ['finance-comments', postId] as const,
  adminFinancePosts: ['admin', 'finance-posts'] as const,
  adminUserDetail: (id: string) => ['admin', 'user', id] as const,
  adminUserGoals: (id: string) => ['admin', 'user', id, 'goals'] as const,
  adminUserTransactions: (id: string) => ['admin', 'user', id, 'transactions'] as const,
  auditLogs: ['admin', 'audit-logs'] as const,
  adminTeam: ['admin', 'team'] as const,
  adminFinanceComments: (postId: string) => ['admin', 'finance-comments', postId] as const,
}
